services:
  postgres:
    image: postgres:16-alpine
    container_name: cyna-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cyna
      POSTGRES_USER: cyna
      POSTGRES_PASSWORD: cyna_dev_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
