apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://cyna-loki:3100
    uid: P8E80F9AEF21F6940
    isDefault: true
    editable: false
    jsonData:
      manageAlerts: false
