{
 "title": "Frontend Health",
 "tags": [
  "cyna",
  "frontend"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Client Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate({app=\"cyna-frontend\",level=\"ERROR\"} [5m]))"
    }
   ]
  },
  {
   "title": "Total Logs / min",
   "type": "stat",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate({app=\"cyna-frontend\"} [5m])) * 60"
    }
   ]
  },
  {
   "title": "API Errors vs JS Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate({app=\"cyna-frontend\",level=\"ERROR\"} |= \"HTTP\" [5m]))",
     "legendFormat": "API Errors"
    },
    {
     "expr": "sum(rate({app=\"cyna-frontend\",level=\"ERROR\"} != \"HTTP\" [5m]))",
     "legendFormat": "JS Errors"
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"cyna-frontend\"}"
    }
   ]
  }
 ]
}